from django.urls import path

from .views import (
    components_bootstrap_alerts_view,
    components_bootstrap_buttons_view,
    components_bootstrap_cards_view,
    components_bootstrap_carousel_view,
    components_bootstrap_dropdowns_view,
    components_bootstrap_grid_view,
    components_bootstrap_images_view,
    components_bootstrap_modals_view,
    components_bootstrap_offcanvas_view,
    components_bootstrap_progressbars_view,
    components_bootstrap_placeholders_view,
    components_bootstrap_tabs_view,
    components_bootstrap_typography_view,
    components_bootstrap_video_view,
    components_bootstrap_general_view,
    components_bootstrap_colors_view,
    components_extended_lightbox_view,
    components_extended_rangeslider_view,
    components_extended_sweetalert_view,
    components_extended_sessiontimeout_view,
    components_extended_rating_view,
    components_extended_notifications_view,
    components_forms_basic_elements_view,
    components_forms_validation_view,
    components_forms_advanced_plugins_view,
    components_forms_editors_view,
    components_forms_fileupload_view,
    components_forms_wizard_view,
    components_forms_mask_view,
    components_tables_bootstrap_basic_view,
    components_tables_datatables_view,
    components_tables_responsive_tables_view,
    components_tables_editable_tables_view,
    components_charts_apexcharts_view,
    components_charts_echarts_view,
    components_charts_chartjs_view,
    components_charts_jqueryknob_view,
    components_charts_sparkline_view,
    components_icons_boxicons_view,
    components_icons_materialdesign_view,
    components_icons_dripicons_view,
    components_icons_fontawesome_view,
    components_icons_feather_view,
    components_maps_googlemaps_view,
    components_maps_vectormaps_view,
    components_maps_leaflet_view,
)

app_name = "components"

urlpatterns = [
    # Components
    path(
        "bootstrap/alerts",
        view=components_bootstrap_alerts_view,
        name="components.bootstrap.alerts",
    ),
    path(
        "bootstrap/buttons",
        view=components_bootstrap_buttons_view,
        name="components.bootstrap.buttons",
    ),
    path(
        "bootstrap/cards",
        view=components_bootstrap_cards_view,
        name="components.bootstrap.cards",
    ),
    path(
        "bootstrap/carousel",
        view=components_bootstrap_carousel_view,
        name="components.bootstrap.carousel",
    ),
    path(
        "bootstrap/dropdowns",
        view=components_bootstrap_dropdowns_view,
        name="components.bootstrap.dropdowns",
    ),
    path(
        "bootstrap/grid",
        view=components_bootstrap_grid_view,
        name="components.bootstrap.grid",
    ),
    path(
        "bootstrap/images",
        view=components_bootstrap_images_view,
        name="components.bootstrap.images",
    ),
    path(
        "bootstrap/modals",
        view=components_bootstrap_modals_view,
        name="components.bootstrap.modals",
    ),
    path(
        "bootstrap/offcanvas",
        view=components_bootstrap_offcanvas_view,
        name="components.bootstrap.offcanvas",
    ),
    path(
        "bootstrap/progressbars",
        view=components_bootstrap_progressbars_view,
        name="components.bootstrap.progressbars",
    ),
    path(
        "bootstrap/placeholders",
        view=components_bootstrap_placeholders_view,
        name="components.bootstrap.placeholders",
    ),
    path(
        "bootstrap/tabs",
        view=components_bootstrap_tabs_view,
        name="components.bootstrap.tabs",
    ),
    path(
        "bootstrap/typography",
        view=components_bootstrap_typography_view,
        name="components.bootstrap.typography",
    ),
    path(
        "bootstrap/video",
        view=components_bootstrap_video_view,
        name="components.bootstrap.video",
    ),
    path(
        "bootstrap/general",
        view=components_bootstrap_general_view,
        name="components.bootstrap.general",
    ),
    path(
        "bootstrap/colors",
        view=components_bootstrap_colors_view,
        name="components.bootstrap.colors",
    ),
    # Extended
    path(
        "extended/lightbox",
        view=components_extended_lightbox_view,
        name="components.extended.lightbox",
    ),
    path(
        "extended/rangeslider",
        view=components_extended_rangeslider_view,
        name="components.extended.rangeslider",
    ),
    path(
        "extended/sweetalerts2",
        view=components_extended_sweetalert_view,
        name="components.extended.sweetalerts2",
    ),
    path(
        "extended/session-timeout",
        view=components_extended_sessiontimeout_view,
        name="components.extended.sessiontimeout",
    ),
    path(
        "extended/rating",
        view=components_extended_rating_view,
        name="components.extended.rating",
    ),
    path(
        "extended/notifications",
        view=components_extended_notifications_view,
        name="components.extended.notifications",
    ),
    # Forms
    path(
        "forms/basic_elements",
        view=components_forms_basic_elements_view,
        name="components.forms.basic_elements",
    ),
    path(
        "forms/validation",
        view=components_forms_validation_view,
        name="components.forms.validation",
    ),
    path(
        "forms/advancedplugins",
        view=components_forms_advanced_plugins_view,
        name="components.forms.advancedplugins",
    ),
    path(
        "forms/editors",
        view=components_forms_editors_view,
        name="components.forms.editors",
    ),
    path(
        "forms/fileupload",
        view=components_forms_fileupload_view,
        name="components.forms.fileupload",
    ),
    path(
        "forms/wizard",
        view=components_forms_wizard_view,
        name="components.forms.wizard",
    ),
    path("forms/mask", view=components_forms_mask_view, name="components.forms.mask"),
    # Tables
    path(
        "tables/bootstrapbasic",
        view=components_tables_bootstrap_basic_view,
        name="components.tables.bootstrap_basic",
    ),
    path(
        "tables/datatables",
        view=components_tables_datatables_view,
        name="components.tables.datatables",
    ),
    path(
        "tables/responsive_tables",
        view=components_tables_responsive_tables_view,
        name="components.tables.responsive_tables",
    ),
    path(
        "tables/editable_tables",
        view=components_tables_editable_tables_view,
        name="components.tables.editable_tables",
    ),
    # Charts
    path(
        "charts/apexcharts",
        view=components_charts_apexcharts_view,
        name="components.charts.apexcharts",
    ),
    path(
        "charts/echarts",
        view=components_charts_echarts_view,
        name="components.charts.echarts",
    ),
    path(
        "charts/chartjs",
        view=components_charts_chartjs_view,
        name="components.charts.chartjs",
    ),
    path(
        "charts/knob",
        view=components_charts_jqueryknob_view,
        name="components.charts.knob",
    ),
    path(
        "charts/sparkline",
        view=components_charts_sparkline_view,
        name="components.charts.sparkline",
    ),
    # Icons
    path(
        "icons/boxicons",
        view=components_icons_boxicons_view,
        name="components.icons.boxicons",
    ),
    path(
        "icons/materialdesign",
        view=components_icons_materialdesign_view,
        name="components.icons.materialdesign",
    ),
    path(
        "icons/dripicons",
        view=components_icons_dripicons_view,
        name="components.icons.dripicons",
    ),
    path(
        "icons/fontawesome",
        view=components_icons_fontawesome_view,
        name="components.icons.fontawesome",
    ),
    path(
        "icons/feather",
        view=components_icons_feather_view,
        name="components.icons.feather",
    ),
    # Maps
    path(
        "maps/googlemaps",
        view=components_maps_googlemaps_view,
        name="components.maps.googlemaps",
    ),
    path(
        "maps/vectormaps",
        view=components_maps_vectormaps_view,
        name="components.maps.vectormaps",
    ),
    path(
        "maps/leaflet",
        view=components_maps_leaflet_view,
        name="components.maps.leaflet",
    ),
]
