# Generated by Django 4.0.6 on 2022-07-28 13:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('logo', models.URLField(blank=True)),
                ('website', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('factsheet', models.URLField(blank=True)),
                ('company_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funds.company')),
            ],
        ),
        migrations.CreateModel(
            name='PriceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('price', models.BigIntegerField()),
                ('marketcap', models.CharField(max_length=250)),
                ('fund_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funds.fund')),
            ],
        ),
    ]
