# Generated by Django 4.0.6 on 2022-07-28 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricedata',
            name='marketcap',
            field=models.BigIntegerField(),
        ),
    ]
