# Generated by Django 4.0.6 on 2022-07-27 18:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('name', models.CharField(max_length=250, primary_key=True, serialize=False, unique=True)),
                ('logo', models.URLField(blank=True)),
                ('marketcap', models.CharField(max_length=250)),
            ],
        ),
        migrations.RemoveField(
            model_name='fund',
            name='marketcap',
        ),
        migrations.AddField(
            model_name='fund',
            name='id',
            field=models.AutoField(default=43, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='fund',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.CreateModel(
            name='PriceData',
            fields=[
                ('id', models.AutoField(default=22, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('price', models.BigIntegerField()),
                ('marketcap', models.CharField(max_length=250)),
                ('fund_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funds.fund')),
            ],
        ),
        migrations.AddField(
            model_name='fund',
            name='company_id',
            field=models.ManyToManyField(blank=True, to='funds.company'),
        ),
    ]
