# Generated by Django 4.0.6 on 2022-07-27 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0002_company_remove_fund_marketcap_fund_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fund',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='fund',
            name='company_id',
        ),
        migrations.AddField(
            model_name='fund',
            name='company_id',
            field=models.ForeignKey(default=8938, on_delete=django.db.models.deletion.CASCADE, to='funds.company'),
        ),
    ]
