# Generated by Django 4.0.6 on 2022-07-28 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0002_alter_pricedata_marketcap'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='funds_managed',
            field=models.ManyToManyField(to='funds.fund', verbose_name='List of funds'),
        ),
        migrations.AddField(
            model_name='fund',
            name='pricing_data',
            field=models.ManyToManyField(to='funds.pricedata', verbose_name='Pricing Data'),
        ),
    ]
