# Generated by Django 4.0.6 on 2022-07-28 13:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0003_company_funds_managed_fund_pricing_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricedata',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='pricedata',
            name='marketcap',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pricedata',
            name='price',
            field=models.IntegerField(),
        ),
    ]
