# Generated by Django 4.0.6 on 2022-07-27 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0003_remove_fund_manager_remove_fund_company_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fund',
            name='company_id',
        ),
        migrations.AddField(
            model_name='fund',
            name='company_id',
            field=models.ManyToManyField(blank=True, to='funds.company'),
        ),
    ]
