# Generated by Django 4.0.6 on 2022-07-28 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0004_remove_fund_company_id_fund_company_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='category',
            field=models.CharField(choices=[('1', 'Bond'), ('2', 'Equity'), ('3', 'Property')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='fund',
            name='risk_profile',
            field=models.CharField(choices=[('1', 'Low'), ('2', 'Medium'), ('3', 'High')], max_length=1, null=True),
        ),
    ]
