# Generated by Django 4.0.6 on 2022-07-28 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0006_alter_fund_id_alter_pricedata_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fund',
            old_name='company_id',
            new_name='company',
        ),
        migrations.AddField(
            model_name='company',
            name='id',
            field=models.BigAutoField(auto_created=True, default=21, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='fund',
            name='category',
            field=models.CharField(blank=True, choices=[('1', 'Bond'), ('2', 'Equity'), ('3', 'Property')], max_length=1),
        ),
        migrations.AlterField(
            model_name='fund',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='risk_profile',
            field=models.CharField(blank=True, choices=[('1', 'Low'), ('2', 'Medium'), ('3', 'Property')], max_length=1),
        ),
        migrations.AlterField(
            model_name='pricedata',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
