# Generated by Django 4.0.6 on 2022-07-31 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0006_alter_pricedata_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricedata',
            name='marketcap',
        ),
        migrations.AddField(
            model_name='pricedata',
            name='factsheet',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='pricedata',
            name='shares',
            field=models.FloatField(blank=True, default=22),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.FileField(upload_to='static/images/funds/'),
        ),
        migrations.AlterField(
            model_name='pricedata',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='pricedata',
            name='price',
            field=models.FloatField(blank=True),
        ),
    ]
