# Generated by Django 4.0.6 on 2022-07-28 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0007_rename_company_id_fund_company_company_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='id',
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=250, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='fund',
            name='id',
            field=models.AutoField(default=43, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pricedata',
            name='id',
            field=models.AutoField(default=22, primary_key=True, serialize=False),
        ),
    ]
