# Generated by Django 4.0.6 on 2022-08-01 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0007_remove_pricedata_marketcap_pricedata_factsheet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='one_month',
            field=models.FloatField(blank=True, default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fund',
            name='one_year',
            field=models.FloatField(blank=True, default=13),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fund',
            name='six_month',
            field=models.FloatField(blank=True, default=14),
            preserve_default=False,
        ),
    ]
