# Generated by Django 4.0.6 on 2022-07-28 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0008_remove_company_id_alter_company_name_alter_fund_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
