# Generated by Django 4.0.6 on 2022-07-28 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0009_alter_fund_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='marketcap',
        ),
        migrations.AlterField(
            model_name='fund',
            name='company',
            field=models.ManyToManyField(blank=True, null=True, to='funds.company'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='risk_profile',
            field=models.CharField(blank=True, choices=[('1', 'Low'), ('2', 'Medium'), ('3', 'Property')], max_length=1, null=True),
        ),
    ]
