# Generated by Django 4.0.6 on 2022-08-01 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0009_remove_fund_pricing_data_fund_market_cap'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='price',
            field=models.FloatField(blank=True, default=22),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fund',
            name='shares',
            field=models.FloatField(blank=True, default=455),
            preserve_default=False,
        ),
    ]
