# Generated by Django 4.0.6 on 2022-08-10 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0010_fund_price_fund_shares'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fund',
            name='factsheet',
        ),
    ]
