# Generated by Django 4.0.6 on 2022-08-10 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0011_remove_fund_factsheet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='company_link',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='funds.company'),
        ),
    ]
