# Generated by Django 4.0.6 on 2022-07-28 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0012_company_id_alter_company_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='id',
        ),
        migrations.RemoveField(
            model_name='fund',
            name='category',
        ),
        migrations.RemoveField(
            model_name='fund',
            name='risk_profile',
        ),
        migrations.AddField(
            model_name='company',
            name='marketcap',
            field=models.CharField(default=443, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fund',
            name='company_id',
            field=models.ManyToManyField(blank=True, to='funds.company'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=250, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='fund',
            name='id',
            field=models.AutoField(default=43, primary_key=True, serialize=False),
        ),
    ]
