# Generated by Django 4.0.6 on 2022-07-28 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0013_remove_company_id_remove_fund_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='price_data',
            field=models.ManyToManyField(blank=True, to='funds.pricedata'),
        ),
    ]
