# Generated by Django 4.0.6 on 2022-08-10 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0013_alter_fund_company_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='market_cap',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fund',
            name='one_month',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fund',
            name='one_year',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fund',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fund',
            name='shares',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fund',
            name='six_month',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
