# Generated by Django 4.0.6 on 2022-08-10 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0014_alter_fund_market_cap_alter_fund_one_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricedata',
            name='market_cap',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
