# Generated by Django 4.0.6 on 2022-08-10 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0015_pricedata_market_cap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricedata',
            name='factsheet',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pricedata',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pricedata',
            name='shares',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
