# Generated by Django 4.0.6 on 2022-09-12 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0016_alter_pricedata_factsheet_alter_pricedata_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='chart',
            field=models.CharField(blank=True, max_length=550, null=True),
        ),
    ]
